/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description The process is up and serving requests. Never checks dependencies, so a database outage
         *     does not make an orchestrator restart a healthy process.
         */
        get: operations["health_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description All dependencies are reachable, so the hub can take traffic. Returns 503 otherwise.
         */
        get: operations["health_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description OAuth2 password flow (form-encoded `username` and `password`). Rate-limited per client.
         */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh tokens
         * @description Exchange a refresh token for a new token pair. The old refresh token stops working.
         */
        post: operations["auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Revoke the refresh token. The current access token expires on its own within minutes.
         */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a stream ticket
         * @description Browsers cannot send an `Authorization` header when opening a WebSocket or an `<img>`
         *     MJPEG stream; they pass this short-lived, single-use ticket as `?ticket=` instead.
         */
        post: operations["auth_issue_ticket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List devices */
        get: operations["devices_list_devices"];
        put?: never;
        /**
         * Add a device
         * @description Starts the camera right away when `enabled`.
         */
        post: operations["devices_create_device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a source
         * @description Open the source and read one frame, without saving anything. A failure is reported in
         *     the body (`ok: false`), not as an HTTP error.
         */
        post: operations["devices_check_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a camera's source
         * @description Open the saved source, with its stored credentials, and read one frame. Like
         *     `POST /devices/test`, a failure is reported in the body. A running camera is already
         *     connected: some sources (USB webcams) cannot be opened twice, so test stopped cameras.
         */
        post: operations["devices_check_device_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a device */
        get: operations["devices_get_device"];
        put?: never;
        post?: never;
        /** Delete a device */
        delete: operations["devices_delete_device"];
        options?: never;
        head?: never;
        /**
         * Update a device
         * @description Only fields present in the body change. Changing the source, detection or frame rate
         *     restarts a running camera.
         */
        patch: operations["devices_update_device"];
        trace?: never;
    };
    "/api/v1/devices/{device_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a camera
         * @description Accepted: the camera connects in the background; watch `status` become `online`.
         */
        post: operations["devices_start_device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a camera */
        post: operations["devices_stop_device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/detection-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace detection settings
         * @description Hot reload: a running camera restarts with the new settings (its background model
         *     re-learns for a moment).
         */
        put: operations["devices_set_detection_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest frame
         * @description At most about a second old (live frames refresh continuously while someone watches).
         */
        get: operations["devices_snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List events
         * @description Newest first. Snapshot links in the response are signed and expire after
         *     `VISION_HUB_SECURITY__SIGNED_URL_TTL_SECONDS`.
         */
        get: operations["events_list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an event */
        get: operations["events_get_event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit entries
         * @description Newest first: who changed which device or user, and when. `request_id` matches the
         *     server logs of the request that made the change.
         */
        get: operations["audit_list_audit_entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the push key
         * @description The hub's public VAPID key, to pass to `pushManager.subscribe()` as the
         *     `applicationServerKey`. 404 when push is turned off on the hub.
         */
        get: operations["push_get_push_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subscribe this browser
         * @description Send `PushSubscription.toJSON()`. Subscribing the same browser again replaces its
         *     entry, under the account signed in now. Endpoints must be on a known push service.
         */
        post: operations["push_subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/push/subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unsubscribe a browser
         * @description The id is the SHA-256 of the endpoint (hex). Only your own subscriptions.
         */
        delete: operations["push_unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/push/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a test notification
         * @description To every browser subscribed under your account. Browsers whose subscription turns out to
         *     have expired are removed and counted in neither number.
         */
        post: operations["push_send_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live MJPEG stream
         * @description Use directly as `<img src=".../stream?ticket=...">`. Ends when the camera stops.
         *
         *     Frames are clean. A part showing motion carries what was detected on it in an
         *     `X-Detections` header: `{"boxes": [[x, y, width, height], ...], "person": 0.87}`, boxes in
         *     fractions of the picture, `person` the score once the open event found a person (else
         *     null). Read the parts yourself to draw them; an `<img>` ignores the header.
         */
        get: operations["devices_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event snapshot
         * @description Use the signed `url` from an event, or a bearer token. Snapshots never change, so
         *     browsers may cache them privately.
         */
        get: operations["events_snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/clip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event clip
         * @description Use the signed `clip.url` from an event, or a bearer token. Supports `Range` requests,
         *     which browsers use to seek (Safari needs them to play at all). Saved files are named after
         *     the camera and the time the event started.
         */
        get: operations["events_clip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Id */
            id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            target_type: components["schemas"]["AuditTarget"];
            /** Target Id */
            target_id: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id: string | null;
        };
        /**
         * AuditTarget
         * @enum {string}
         */
        AuditTarget: "device" | "user";
        /** Body_auth_login */
        Body_auth_login: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * BoundingBox
         * @description Axis-aligned box in pixel coordinates of the original (full-resolution) frame.
         */
        BoundingBox: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** CheckStatus */
        CheckStatus: {
            /** Name */
            name: string;
            /** Healthy */
            healthy: boolean;
            /** Duration Ms */
            duration_ms: number;
        };
        /** ClipLink */
        ClipLink: {
            /**
             * Url
             * @description Signed, expiring link: usable directly in a <video> tag
             */
            url: string;
            /**
             * Content Type
             * @description "video/webm" (VP8)
             */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** DetectionConfig */
        DetectionConfig: {
            /**
             * Min Motion Area
             * @default 0.01
             */
            min_motion_area: number;
            /**
             * Pixel Threshold
             * @default 60
             */
            pixel_threshold: number;
            /**
             * Blur Kernel Size
             * @default 21
             */
            blur_kernel_size: number;
            /**
             * Roi
             * @description Regions to watch; empty means the whole frame
             * @default []
             */
            roi: components["schemas"]["Polygon"][];
            /**
             * Processing Width
             * @default 640
             */
            processing_width: number;
            /**
             * Background Learning Rate
             * @default 0.02
             */
            background_learning_rate: number;
            /**
             * Warmup Frames
             * @default 10
             */
            warmup_frames: number;
            /**
             * Lighting Change Ratio
             * @default 0.6
             */
            lighting_change_ratio: number;
            /**
             * Min Motion Frames
             * @default 2
             */
            min_motion_frames: number;
            /**
             * Motion End Grace Seconds
             * @default 2
             */
            motion_end_grace_seconds: number;
            /**
             * Max Event Seconds
             * @default 120
             */
            max_event_seconds: number;
            /**
             * Alert On
             * @default motion
             * @enum {string}
             */
            alert_on: "motion" | "person";
        };
        /** DeviceCreate */
        DeviceCreate: {
            id: components["schemas"]["DeviceId"];
            /** Name */
            name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Target Fps */
            target_fps?: number | null;
            /** Retention Days */
            retention_days?: number | null;
            source: components["schemas"]["SourceConfig-Input"];
            /** @description Omit to use the hub-wide defaults */
            detection?: components["schemas"]["DetectionConfig"] | null;
        };
        DeviceId: string;
        /** DeviceOut */
        DeviceOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Enabled
             * @description Started automatically when the hub starts
             */
            enabled: boolean;
            /**
             * Target Fps
             * @description Analysed frames per second; null = default
             */
            target_fps: number | null;
            /**
             * Retention Days
             * @description Days events are kept; null = hub default
             */
            retention_days: number | null;
            source: components["schemas"]["SourceConfig-Output"];
            detection: components["schemas"]["DetectionConfig"];
            status: components["schemas"]["DeviceStatus"];
            /** Running */
            running: boolean;
            /** @description Latest live frame, if the camera produced one */
            stream: components["schemas"]["StreamInfo"] | null;
            last_event: components["schemas"]["LastEvent"] | null;
        };
        /**
         * DeviceStatus
         * @enum {string}
         */
        DeviceStatus: "stopped" | "starting" | "online" | "reconnecting" | "failed";
        /**
         * DeviceUpdate
         * @description Partial update: only the fields present in the request change.
         */
        DeviceUpdate: {
            /** Name */
            name?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Target Fps */
            target_fps?: number | null;
            /** Retention Days */
            retention_days?: number | null;
            source?: components["schemas"]["SourceConfig-Input"] | null;
            detection?: components["schemas"]["DetectionConfig"] | null;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: string;
            /** Device Id */
            device_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /**
             * Complete
             * @description True once the event has ended
             */
            complete: boolean;
            /**
             * Interrupted
             * @description The hub stopped abruptly before the event ended
             */
            interrupted: boolean;
            /**
             * Peak Area Ratio
             * @description Largest moving region, as a fraction of the frame
             */
            peak_area_ratio: number;
            /** Motion Frames */
            motion_frames: number;
            /**
             * Person
             * @description A person was seen; null when nobody could check (detection off, no model)
             */
            person: boolean | null;
            /**
             * Person Confidence
             * @description Best person score of the checks
             */
            person_confidence: number | null;
            /**
             * Alert
             * @description Raised an alert (false: the camera alerts on people only and none was seen)
             */
            alert: boolean;
            /** Boxes */
            boxes: components["schemas"]["BoundingBox"][];
            /** Snapshots */
            snapshots: components["schemas"]["SnapshotLink"][];
            /** @description Video of the event, from a few seconds before it was detected */
            clip: components["schemas"]["ClipLink"] | null;
        };
        /**
         * FieldError
         * @description One request validation failure. The offending input is deliberately omitted.
         */
        FieldError: {
            /**
             * Loc
             * @description Path to the invalid field, e.g. ['body', 'port']
             */
            loc: (string | number)[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        };
        /** @enum {string} */
        ImageKind: "clean" | "annotated" | "thumbnail";
        /** LastEvent */
        LastEvent: {
            /** Id */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Peak Area Ratio */
            peak_area_ratio: number;
        };
        /** Liveness */
        Liveness: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** Page[AuditEntryOut] */
        Page_AuditEntryOut_: {
            /** Items */
            items: components["schemas"]["AuditEntryOut"][];
            /**
             * Next Cursor
             * @description Pass as `cursor` to fetch the next page; null on the last page
             */
            next_cursor: string | null;
        };
        /** Page[DeviceOut] */
        Page_DeviceOut_: {
            /** Items */
            items: components["schemas"]["DeviceOut"][];
            /**
             * Next Cursor
             * @description Pass as `cursor` to fetch the next page; null on the last page
             */
            next_cursor: string | null;
        };
        /** Page[EventOut] */
        Page_EventOut_: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /**
             * Next Cursor
             * @description Pass as `cursor` to fetch the next page; null on the last page
             */
            next_cursor: string | null;
        };
        Point: [
            number,
            number
        ];
        Polygon: components["schemas"]["Point"][];
        /** PrincipalOut */
        PrincipalOut: {
            /** Username */
            username: string;
            role: components["schemas"]["Role"];
        };
        /** ProblemDetail */
        ProblemDetail: {
            /**
             * Type
             * @description URI identifying the problem type
             * @default about:blank
             * @example about:blank
             */
            type: string;
            /**
             * Title
             * @description Short, human-readable summary of the problem type
             */
            title: string;
            /**
             * Status
             * @description HTTP status code
             */
            status: number;
            /**
             * Detail
             * @description Explanation specific to this occurrence
             * @default null
             */
            detail: string | null;
            /**
             * Instance
             * @description Request path that produced the problem
             * @default null
             */
            instance: string | null;
            /**
             * Request Id
             * @description Correlates with server logs
             * @default null
             */
            request_id: string | null;
            /**
             * Errors
             * @description Validation failures
             * @default null
             */
            errors: components["schemas"]["FieldError"][] | null;
        } & {
            [key: string]: unknown;
        };
        /** PushConfigOut */
        PushConfigOut: {
            /**
             * Public Key
             * @description `applicationServerKey` to subscribe with
             */
            public_key: string;
        };
        /** PushKeysIn */
        PushKeysIn: {
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
        };
        /** PushSubscriptionIn */
        PushSubscriptionIn: {
            /** Endpoint */
            endpoint: string;
            keys: components["schemas"]["PushKeysIn"];
            /** Expirationtime */
            expirationTime?: number | null;
        };
        /** PushSubscriptionOut */
        PushSubscriptionOut: {
            /**
             * Id
             * @description SHA-256 of the endpoint, hex
             */
            id: string;
            created_at: components["schemas"]["UtcDateTime"];
        };
        /** PushTestOut */
        PushTestOut: {
            /**
             * Delivered
             * @description Browsers whose push service accepted it
             */
            delivered: number;
            /**
             * Failed
             * @description Push service unreachable or refused it
             */
            failed: number;
        };
        /** Readiness */
        Readiness: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
            /** Checks */
            checks: components["schemas"]["CheckStatus"][];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * Role
         * @description Ordered from least to most privileged; a higher role includes every lower one.
         * @enum {string}
         */
        Role: "viewer" | "admin";
        /**
         * RtspSourceConfig
         * @description Credentials live in their own fields so they stay secret; ``url`` must not embed them.
         */
        "RtspSourceConfig-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rtsp";
            /**
             * Url
             * @example rtsp://192.168.1.20:554/stream1
             */
            url: string;
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
            /**
             * Open Timeout Seconds
             * @default 10
             */
            open_timeout_seconds: number;
            /**
             * Read Timeout Seconds
             * @default 10
             */
            read_timeout_seconds: number;
        };
        /**
         * RtspSourceConfig
         * @description Credentials live in their own fields so they stay secret; ``url`` must not embed them.
         */
        "RtspSourceConfig-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rtsp";
            /**
             * Url
             * @example rtsp://192.168.1.20:554/stream1
             */
            url: string;
            /** Username */
            username?: string | null;
            /**
             * Open Timeout Seconds
             * @default 10
             */
            open_timeout_seconds: number;
            /**
             * Read Timeout Seconds
             * @default 10
             */
            read_timeout_seconds: number;
            /** Has Password */
            readonly has_password: boolean;
        };
        /** SnapshotLink */
        SnapshotLink: {
            kind: components["schemas"]["ImageKind"];
            /**
             * Url
             * @description Signed, expiring link: usable directly in an <img> tag
             */
            url: string;
            /** Size Bytes */
            size_bytes: number;
        };
        "SourceConfig-Input": components["schemas"]["WebcamSourceConfig"] | components["schemas"]["RtspSourceConfig-Input"] | components["schemas"]["VideoFileSourceConfig"] | components["schemas"]["SyntheticSourceConfig"];
        "SourceConfig-Output": components["schemas"]["WebcamSourceConfig"] | components["schemas"]["RtspSourceConfig-Output"] | components["schemas"]["VideoFileSourceConfig"] | components["schemas"]["SyntheticSourceConfig"];
        /** SourceTestRequest */
        SourceTestRequest: {
            source: components["schemas"]["SourceConfig-Input"];
        };
        /** SourceTestResult */
        SourceTestResult: {
            /** Ok */
            ok: boolean;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Fps */
            fps: number | null;
            /** Error */
            error: string | null;
        };
        /** StreamInfo */
        StreamInfo: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Last Frame At
             * Format: date-time
             */
            last_frame_at: string;
        };
        /**
         * SyntheticSourceConfig
         * @description Generated scene with a figure that walks through periodically; no hardware needed.
         */
        SyntheticSourceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "synthetic";
            /**
             * Width
             * @default 640
             */
            width: number;
            /**
             * Height
             * @default 480
             */
            height: number;
            /**
             * Fps
             * @default 10
             */
            fps: number;
            /**
             * Visit Every Seconds
             * @description Time between visits
             * @default 20
             */
            visit_every_seconds: number;
            /**
             * Visit Seconds
             * @description How long each visit lasts
             * @default 5
             */
            visit_seconds: number;
            /**
             * Seed
             * @description Fixes the sensor noise, for tests
             */
            seed?: number | null;
        };
        /** TicketOut */
        TicketOut: {
            /**
             * Ticket
             * @description Single use; pass as ?ticket= to a WebSocket or stream URL
             */
            ticket: string;
            /**
             * Expires In
             * @description Seconds until the ticket expires
             */
            expires_in: number;
        };
        /**
         * TokenResponse
         * @description OAuth2 token response (RFC 6749 §5.1), plus the refresh token's lifetime.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Expires In
             * @description Access token lifetime in seconds
             */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Refresh Expires In
             * @description Refresh token lifetime in seconds
             */
            refresh_expires_in: number;
        };
        /** Format: date-time */
        UtcDateTime: string;
        /** VideoFileSourceConfig */
        VideoFileSourceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "video_file";
            /**
             * Path
             * Format: path
             */
            path: string;
            /**
             * Loop
             * @default true
             */
            loop: boolean;
        };
        /** WebcamSourceConfig */
        WebcamSourceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "webcam";
            /**
             * Index
             * @description OS capture device index
             * @default 0
             */
            index: number;
            /**
             * Width
             * @description Requested width
             */
            width?: number | null;
            /**
             * Height
             * @description Requested height
             */
            height?: number | null;
            /**
             * Fps
             * @description Requested frame rate
             */
            fps?: number | null;
        };
        /** DeviceStatusData */
        DeviceStatusData: {
            status: components["schemas"]["DeviceStatus"];
        };
        /** DeviceStatusMessage */
        DeviceStatusMessage: {
            /**
             * V
             * @default 1
             * @constant
             */
            v: 1;
            ts: components["schemas"]["UtcDateTime"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "device.status";
            /** Device Id */
            device_id: string;
            data: components["schemas"]["DeviceStatusData"];
        };
        /** ErrorData */
        ErrorData: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorMessage */
        ErrorMessage: {
            /**
             * V
             * @default 1
             * @constant
             */
            v: 1;
            ts: components["schemas"]["UtcDateTime"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            data: components["schemas"]["ErrorData"];
        };
        /** MotionEndedData */
        MotionEndedData: {
            /** Event Id */
            event_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Peak Area Ratio */
            peak_area_ratio: number;
            /** Motion Frames */
            motion_frames: number;
            /** Boxes */
            boxes: components["schemas"]["BoundingBox"][];
            /**
             * Person
             * @description A person was seen; null when nobody could check
             */
            person: boolean | null;
            /** Person Confidence */
            person_confidence: number | null;
            /**
             * Alert
             * @description Show an alert (false: people only, and none was seen)
             */
            alert: boolean;
        };
        /** MotionEndedMessage */
        MotionEndedMessage: {
            /**
             * V
             * @default 1
             * @constant
             */
            v: 1;
            ts: components["schemas"]["UtcDateTime"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "motion.ended";
            /** Device Id */
            device_id: string;
            /**
             * Replay
             * @default false
             */
            replay: boolean;
            data: components["schemas"]["MotionEndedData"];
        };
        /** MotionStartedData */
        MotionStartedData: {
            /** Event Id */
            event_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** MotionStartedMessage */
        MotionStartedMessage: {
            /**
             * V
             * @default 1
             * @constant
             */
            v: 1;
            ts: components["schemas"]["UtcDateTime"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "motion.started";
            /** Device Id */
            device_id: string;
            /**
             * Replay
             * @default false
             */
            replay: boolean;
            data: components["schemas"]["MotionStartedData"];
        };
        /** PingMessage */
        PingMessage: {
            /**
             * V
             * @default 1
             * @constant
             */
            v: 1;
            ts: components["schemas"]["UtcDateTime"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ping";
        };
        /** ReplayDoneData */
        ReplayDoneData: {
            /** Count */
            count: number;
            /**
             * Truncated
             * @description More events were missed than replayed; use the API
             */
            truncated: boolean;
        };
        /** ReplayDoneMessage */
        ReplayDoneMessage: {
            /**
             * V
             * @default 1
             * @constant
             */
            v: 1;
            ts: components["schemas"]["UtcDateTime"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "replay.done";
            data: components["schemas"]["ReplayDoneData"];
        };
        /** SubscriptionData */
        SubscriptionData: {
            /**
             * Devices
             * @description Subscribed devices; null means all
             */
            devices: string[] | null;
            /**
             * Excluded
             * @description Devices excluded while subscribed to all
             */
            excluded: string[];
        };
        /** SubscriptionMessage */
        SubscriptionMessage: {
            /**
             * V
             * @default 1
             * @constant
             */
            v: 1;
            ts: components["schemas"]["UtcDateTime"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "subscription";
            data: components["schemas"]["SubscriptionData"];
        };
        WsServerMessage: components["schemas"]["MotionStartedMessage"] | components["schemas"]["MotionEndedMessage"] | components["schemas"]["DeviceStatusMessage"] | components["schemas"]["SubscriptionMessage"] | components["schemas"]["ReplayDoneMessage"] | components["schemas"]["PingMessage"] | components["schemas"]["ErrorMessage"];
        /** PongMessage */
        PongMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pong";
        };
        /**
         * ResumeMessage
         * @description After reconnecting: replay events newer than the last one the client saw.
         */
        ResumeMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "resume";
            /**
             * After
             * Format: uuid
             */
            after: string;
        };
        /**
         * SubscribeMessage
         * @description Replace the subscription. ``devices: null`` (or omitted) means every device.
         */
        SubscribeMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "subscribe";
            /**
             * Devices
             * @default null
             */
            devices: string[] | null;
        };
        /** UnsubscribeMessage */
        UnsubscribeMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "unsubscribe";
            /** Devices */
            devices: string[];
        };
        WsClientMessage: components["schemas"]["SubscribeMessage"] | components["schemas"]["UnsubscribeMessage"] | components["schemas"]["PongMessage"] | components["schemas"]["ResumeMessage"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    health_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    auth_issue_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_list_devices: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DeviceOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_create_device: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_check_source: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceTestResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_check_device_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceTestResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_get_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_delete_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_update_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_start_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_stop_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_set_detection_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectionConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG of the latest live frame */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    events_list_events: {
        parameters: {
            query?: {
                device_id?: string | null;
                /** @description Started at or after (UTC) */
                since?: components["schemas"]["UtcDateTime"] | null;
                /** @description Started before (UTC) */
                until?: components["schemas"]["UtcDateTime"] | null;
                /** @description Only events with (true) or without (false) a person seen */
                person?: boolean | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EventOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    events_get_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    audit_list_audit_entries: {
        parameters: {
            query?: {
                target_type?: components["schemas"]["AuditTarget"] | null;
                target_id?: string | null;
                actor?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditEntryOut_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    push_get_push_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushConfigOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    push_subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    push_unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    push_send_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushTestOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    devices_stream: {
        parameters: {
            query?: {
                /** @description Frame rate cap */
                fps?: number | null;
                /** @description Single-use ticket from POST /api/v1/auth/tickets */
                ticket?: string | null;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One JPEG per multipart part */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "multipart/x-mixed-replace; boundary=frame": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    events_snapshot: {
        parameters: {
            query?: {
                kind?: "clean" | "annotated" | "thumbnail";
                /** @description From a signed link */
                expires?: number | null;
                /** @description From a signed link */
                signature?: string | null;
            };
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    events_clip: {
        parameters: {
            query?: {
                /** @description From a signed link */
                expires?: number | null;
                /** @description From a signed link */
                signature?: string | null;
            };
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebM video (VP8) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/webm": unknown;
                };
            };
            /** @description The requested byte range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/webm": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Range Not Satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
